#ifndef GERMAN_H
#define GERMAN_H

const char* defaultBatStat[] = {"AKKU_OK", "UBERSTROM", "UBERSPANNUNG" , "UNTERSPANNUNG" , "UNTERLADUNG", "UBERLADUNG" , "UBERHITZUNG", "EINFRIEREN", "KURZSHLUSS"};

#endif